### ISSUE TITLE
const exports in index.js causing issues

### ISSUE THREAD

**Issue by jschloer** [exponent/react-native-action-sheet#26]
Ran into an issue when running Jest tests(v 15.0).

SyntaxError: Identifier 'exports' has already been declared

Looks like my use of const exports in the index.js wasn't a good idea. Seemed to work fine in react-native, but Jest was failing due to the exports alias for node modules being redefined. My bad. I'll be submitting a pull request in a moment that goes back to the old syntax for index.js, but keeps the new provider/connect additions.

For the record Jest doesn't seem to fail on newer versions(was fine on 17), so this may not be much of a problem, but I could see it causing issues down the line.

**Comment by jschloer** [comment]
I take it back about it working on Jest 17 and up, seems to be causing problems there as well. Must have been running a cached version of the module at that point.

**Comment by sibelius** [comment]
@jschloer can we close this?

**Comment by jschloer** [comment]
I don't think so, I think the ```const exports``` I introduced was a bad idea in general and would suggest merging in #27. This keeps the additional exports added by #23, but does so by just extending module.exports.

**Comment by morungos** [comment]
This is a blocker on Jest testing for me, is there anything we can do to move it forward? Or is there some workaround (short of forking the whole repo) a Jest user can point me to?

**Comment by brentvatne** [comment]
Pushed 0.3.1 of @expo/react-native-action-sheet, which includes changes from #27, that should resolve the issue

**Comment by jschloer** [comment]
Thanks Brent. Sorry about causing the problem in the first place.

**Comment by morungos** [comment]
Just confirming, issue resolved. Jest tests now pass fine.
