### ISSUE TITLE
@connectActionSheet do not copy statics

### ISSUE THREAD

**Issue by sibelius** [exponent/react-native-action-sheet#34]
I'm using `@connectActionSheet` in a Route component of ex-navigation

and the wrapped component does not have the `static route`.

I can send a PR using this package https://github.com/mridgway/hoist-non-react-statics if this makes sense

**Comment by sibelius** [comment]
something like this: https://github.com/exponent/ex-navigation/blob/master/src/ExNavigationConnect.js#L46

**Comment by mrpatiwi** [comment]
+1, broke my integration with `react-navigation`
